Setup tests.
davefp/handsome pull request #16
Opened 2016-05-31 07:39 UTC by adilfulara

**Summary**
- Add travis CI yml
- Add travis ci build badge
- Add coveralls integration for coverage badge
- Add nyc, mocha, chai and ignore-styles, enzyme, jsdom & react-addons-test-utils npm packages
- Add npm scripts cover and cover:report
- Add test/setup.js to setup dom for enzyme.mount()
- Add tests for number_widget.jsx

**Todo for upstream maintainer:** 
- Update README for urls to coveralls and travis ci to accurate badge numbers.

2016-05-31 19:25 UTC, adilfulara commented
Badges are driving by 

https://coveralls.io/github/adilfulara/handsome
https://travis-ci.org/adilfulara/handsome

2016-10-04 18:42 UTC, stephenyeargin requested changes

2016-10-04 18:42 UTC, stephenyeargin commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/adilfulara/handsome/badge.svg?branch=test-setup)](https://coveralls.io/github/adilfulara/handsome?branch=test-setup)
Would likely want to change the username on these to `davefp` before merging for practical reasons.

2016-11-06 19:35 UTC, merged

2016-11-06 19:36 UTC, davefp commented
Thanks @adilfulara, sorry this took so long for me to get round too

2016-11-06 19:39 UTC, adilfulara commented
@davefp I forgot to do the changes suggested by @stephenyeargin.

2016-11-06 19:40 UTC, davefp commented
I'll do it directly 👍